# Basics of PyTorch

## 00. PyTorch Fundamental

In [108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import torch

print(torch.__version__)

2.9.1+cpu


## Introduction to Tensors

### Creating Tensors

In [109]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [110]:
scalar.ndim

0

In [10]:
#Get Tensor back as Python int

scalar.item()

7

In [31]:
#Vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [32]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [55]:
#Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [56]:
MATRIX.ndim

2

In [57]:
print(MATRIX[0],MATRIX[1])

tensor([7, 8]) tensor([ 9, 10])


In [58]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
#Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random TENSORS

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers`

In [78]:
#Create a random Tensors of shape (3,4)

random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.3663, 0.2150, 0.6472, 0.9985],
         [0.1539, 0.3480, 0.4289, 0.0534],
         [0.0284, 0.3148, 0.5545, 0.4466]],

        [[0.6482, 0.0667, 0.1100, 0.0772],
         [0.6651, 0.2438, 0.6422, 0.7275],
         [0.6821, 0.4267, 0.4492, 0.3082]],

        [[0.3819, 0.9942, 0.2700, 0.8716],
         [0.1635, 0.0030, 0.9123, 0.7517],
         [0.9457, 0.6465, 0.2516, 0.4320]]])

In [75]:
random_tensor.ndim

3

In [81]:
#Create a random Tensor with similar shape to an image Tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #color channels (Red, Green, Blue), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [82]:
#Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

zeros*random_tensor

In [84]:
#Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
ones.dtype

torch.float32

In [86]:
random_tensor.dtype

torch.float32

### Creating a range of TENSORS and TENSORS-like

In [90]:
#Use torch.range()
torch.arange(0,10)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
zero_to_thousand = torch.arange(start = 0, end = 1001, step = 150)
zero_to_thousand

tensor([  0, 150, 300, 450, 600, 750, 900])

In [96]:
# Creating TENSORS like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
ten_zeroses = torch.ones_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR datatypes

In [112]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None, #what datatype is the Tensor (e.g. float32 or float16)
                               device = "cpu", #what devices is yor tensor on
                               requires_grad = False) #whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [101]:
float_32_tensor.dtype

torch.float32

In [114]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [115]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])