# Basics of PyTorch

## 00. PyTorch Fundamental

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import torch

print(torch.__version__)

2.9.1+cu126


## Introduction to Tensors

### Creating Tensors

In [47]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [48]:
scalar.ndim

0

In [49]:
#Get Tensor back as Python int

scalar.item()

7

In [50]:
#Vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [51]:
vector.ndim

1

In [52]:
vector.shape

torch.Size([2])

In [53]:
#Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [54]:
MATRIX.ndim

2

In [55]:
print(MATRIX[0],MATRIX[1])

tensor([7, 8]) tensor([ 9, 10])


In [56]:
MATRIX.shape

torch.Size([2, 2])

In [57]:
#Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [58]:
TENSOR.ndim

3

In [59]:
TENSOR.shape

torch.Size([1, 3, 3])

In [60]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random TENSORS

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers`

In [61]:
#Create a random Tensors of shape (3,4)

random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.7081, 0.0892, 0.1419, 0.9591],
         [0.0992, 0.6333, 0.9595, 0.8270],
         [0.7724, 0.5790, 0.5068, 0.1697]],

        [[0.3999, 0.3310, 0.8126, 0.6953],
         [0.4389, 0.4915, 0.0887, 0.7947],
         [0.0058, 0.7456, 0.3717, 0.8348]],

        [[0.2154, 0.9373, 0.7115, 0.2164],
         [0.7903, 0.9960, 0.4606, 0.8377],
         [0.3685, 0.6726, 0.5550, 0.2950]]])

In [62]:
random_tensor.ndim

3

In [63]:
#Create a random Tensor with similar shape to an image Tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #color channels (Red, Green, Blue), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [64]:
#Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

zeros*random_tensor

In [65]:
#Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
ones.dtype

torch.float32

In [67]:
random_tensor.dtype

torch.float32

### Creating a range of TENSORS and TENSORS-like

In [68]:
#Use torch.range()
torch.arange(0,10)
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
zero_to_thousand = torch.arange(start = 0, end = 1001, step = 150)
zero_to_thousand

tensor([  0, 150, 300, 450, 600, 750, 900])

In [70]:
# Creating TENSORS like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
ten_zeroses = torch.ones_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR datatypes

In [72]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None, #what datatype is the Tensor (e.g. float32 or float16)
                               device = "cpu", #what devices is yor tensor on
                               requires_grad = False) #whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32

In [74]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [75]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [76]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [77]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [78]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4438, 0.2875, 0.1871, 0.5458],
        [0.4129, 0.2261, 0.0618, 0.5702],
        [0.8413, 0.2040, 0.8044, 0.5235]])

In [79]:
# Find out detail about some_tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape, some_tensor.size())
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.4438, 0.2875, 0.1871, 0.5458],
        [0.4129, 0.2261, 0.0618, 0.5702],
        [0.8413, 0.2040, 0.8044, 0.5235]])
torch.float32
torch.Size([3, 4]) torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Sutraction
* Multiplication (element-wise)
* Diviation
* Matrix multiplication

In [80]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [81]:
# Multiply Tensor by 10
tensor = tensor * 10

In [82]:
tensor

tensor([10, 20, 30])

In [83]:
tensor -10

tensor([ 0, 10, 20])

In [84]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [85]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [86]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equal {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equal tensor([100, 400, 900])


In [87]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [88]:
%%time
value = 0
for i in range (0, len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 293 μs


tensor(1400)

In [89]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 62.7 μs


tensor(1400)

### One of the most common errors in deep learning

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm is the same as torch.matmul (it's an alies for writing less code)
torch.matmul(tensor_A, tensor_B) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [90]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our Tensor shape issues, we can manipulate the shape of one of our Tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given Tensor.

In [91]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [92]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [93]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

torch.matmul(tensor_A, tensor_B.T).shape

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (Tensor aggregation)

In [94]:
# Create a Tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [95]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [96]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [97]:
# Find the mean - note: the torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

## Finding the positional min and max

In [98]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [99]:
# Find the position in Tensor that has the minimum value with argmin() -> return index position of target Tensor where the minimum value occurs
x.argmin()

tensor(0)

In [100]:
x[0]

tensor(1)

In [101]:
# Find the position in Tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [102]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsqueezing Tensors

* Reshaping - reshapes an input Tensor to a defined shape
* View - Return a view of an input Tensor of certain shape but keep the same memory as the original Tenosr
* Stacking - combine multiple Tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a Tensor
* Unsqueeze - add a '1' dimension to a target Tensor
* Permute - return a view of the input with dimensions 

In [128]:
# Let's create a Tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [130]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [132]:
# Change a view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [141]:
# Changing z changes x (because a view of a Tensor shares the same memory as the original input)
z[:, 0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [143]:
# Stack Tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [144]:
# torch.squeeze() - removes all single dimensions from a target Tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [145]:
x_reshaped.shape

torch.Size([1, 9])

In [149]:
x_squeezed = x_reshaped.squeeze()

In [150]:
x_reshaped.squeeze().shape

torch.Size([9])

In [153]:
# torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)

print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [156]:
# torch.permute - rearranges the dimensions of a target Tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shift axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"original: {x_original.shape}")
print(f"permuted: {x_permuted.shape}")

original: torch.Size([224, 224, 3])
permuted: torch.Size([3, 224, 224])
